In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[3.0041e-38, 9.0804e-43, 3.0041e-38],
        [9.0804e-43, 3.0041e-38, 9.0804e-43],
        [3.0041e-38, 9.0804e-43, 3.0041e-38],
        [9.0804e-43, 3.0041e-38, 9.0804e-43],
        [3.0041e-38, 9.0804e-43, 3.0041e-38]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.2133, 0.8813, 0.2364],
        [0.3221, 0.0105, 0.3557],
        [0.1957, 0.7466, 0.5989],
        [0.8228, 0.4825, 0.1550],
        [0.8402, 0.1217, 0.6871]])


In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.5644, -0.5918,  0.3476],
        [-0.7169, -1.9980, -0.8904],
        [ 0.5549,  0.4684, -0.2964],
        [-2.1568,  0.3083,  1.2181],
        [-1.4395,  0.5490,  0.3856]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.2319, -0.4789,  0.5201],
        [ 0.1903, -1.8378, -0.1956],
        [ 0.6864,  1.1065, -0.1196],
        [-1.6666,  1.1321,  1.9909],
        [-0.4584,  0.6876,  0.9240]])


In [11]:
print(torch.add(x,y))

tensor([[-0.2319, -0.4789,  0.5201],
        [ 0.1903, -1.8378, -0.1956],
        [ 0.6864,  1.1065, -0.1196],
        [-1.6666,  1.1321,  1.9909],
        [-0.4584,  0.6876,  0.9240]])


In [12]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[-0.2319, -0.4789,  0.5201],
        [ 0.1903, -1.8378, -0.1956],
        [ 0.6864,  1.1065, -0.1196],
        [-1.6666,  1.1321,  1.9909],
        [-0.4584,  0.6876,  0.9240]])


In [13]:
y.add_(x)
print(y)

tensor([[-0.2319, -0.4789,  0.5201],
        [ 0.1903, -1.8378, -0.1956],
        [ 0.6864,  1.1065, -0.1196],
        [-1.6666,  1.1321,  1.9909],
        [-0.4584,  0.6876,  0.9240]])


In [16]:
print(x[:,1])

tensor([-0.5918, -1.9980,  0.4684,  0.3083,  0.5490])


In [19]:
x = torch.randn(4,4)
y = x.view(16)
print(y)
z = x.view(-1,8)
print(z)
print(x.size(), y.size(), z.size())

tensor([-1.4860, -1.0257,  0.1185,  0.0276,  0.3223, -0.2143, -0.1761,  0.1359,
         0.1566, -1.4024, -0.8281, -1.6188, -0.3498,  0.4316, -0.3500,  1.1164])
tensor([[-1.4860, -1.0257,  0.1185,  0.0276,  0.3223, -0.2143, -0.1761,  0.1359],
        [ 0.1566, -1.4024, -0.8281, -1.6188, -0.3498,  0.4316, -0.3500,  1.1164]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4677])
0.46765023469924927


In [ ]:
import torch

In [35]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [36]:
y = x + 2 
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [37]:
print(y.grad_fn)

In [38]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [39]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [40]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [32]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x * 2

while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 0.0877, -0.2474, -0.9205], requires_grad=True)
tensor([ 0.1755, -0.4948, -1.8409], grad_fn=<MulBackward0>)
tensor([  179.7080,  -506.6505, -1885.0853], grad_fn=<MulBackward0>)


In [30]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [41]:
x = torch.tensor([2., 1.], requires_grad=True).view(1, 2)
print(x)
y = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)
print(y)

tensor([[2., 1.]], grad_fn=<ViewBackward>)
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
