In [6]:
import numpy as np

Time = np.ones(10)
print(Time)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
x = 0
#print(len(Time))
ii = range(len(Time))
print(ii)
for i in range(len(Time)):
    x = x + Time
    print(x)

range(0, 10)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
[9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
